services:
  project-management-api:
    container_name: project-management-api
    image :  0li2003/project_management_api:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - SPRING_FLYWAY_USER=${DB_USERNAME}
      - SPRING_FLYWAY_PASSWORD=${DB_PASSWORD}
      - SPRING_FLYWAY_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH}
      - MAIL_SMTP_STARTTLS_ENABLE=${MAIL_SMTP_STARTTLS_ENABLE}
      - MAIL_SMTP_HOST=${MAIL_SMTP_HOST}
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
      - MAIL_SMTP_SSL_TRUST=${MAIL_SMTP_SSL_TRUST}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    depends_on:
      - project-management-db
    networks:
      - project_management_network

  project-management-db:
    image: postgres:latest
    container_name: project-management-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - project_management_volume:/var/lib/postgresql/data
    networks:
      - project_management_network

networks:
  project_management_network:
    driver: bridge

volumes:
  project_management_volume:

